export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL'

export const FETCH_DETAIL_REQUEST = 'FETCH_DETAIL_REQUEST'
export const FETCH_DETAIL_SUCCESS ='FETCH_DETAIL_SUCCESS'
export const FETCH_DETAIL_FAIL ='FETCH_DETAIL_FAIL'


