export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL'

export const FETCH_DETAIL_REQUEST = 'FETCH_DETAIL_REQUEST'
export const FETCH_DETAIL_SUCCESS ='FETCH_DETAIL_SUCCESS'
export const FETCH_DETAIL_FAIL ='FETCH_DETAIL_FAIL'

export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'
export const USER_SIGNIN_SIGNOUT = 'USER_SIGNIN_SIGNOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const CART_ADD_SHIPPING_ADDRESS = 'CART_ADD_SHIPPING_ADDRESS'

export const ORDER_REQUEST = 'ORDER_REQUEST'
export const ORDER_SUCCESS = 'ORDER_SUCCESS'
export const ORDER_FAIL = 'ORDER_FAIL'
export const ORDER_RESET = 'ORDER_RESET'

export const CART_EMPTY = 'CART_EMPTY'

export const ORDER_HISTORY_REQUEST = 'ORDER_HISTORY_REQUEST'
export const ORDER_HISTORY_SUCCESS = 'ORDER_HISTORY_SUCCESS'
export const ORDER_HISTORY_FAIL = 'ORDER_HISTORY_FAIL'